Gen report from check
adevinta/security-overview pull request #10
Opened 2020-08-14 07:44 UTC by manelmontilla

This PR adds a new functionality in the vulcan-security-overview that allows to generate a full report from the output generated by a check.
The functionality is intended to be used while developing a check locally, so it is easy to see how the vulnerabilities generated by the check look in the full report.
This is an example of the command using the new functionality:
```

vulcan-security-overview -config security-overview.toml -check check_report.json 
```

2020-08-25 16:39 UTC, filewalkwithme requested changes
Just minor issues. In general the PR looks good.

2020-08-25 16:39 UTC, filewalkwithme commented on cmd/vulcan-security-overview/main.go
> +	check      = flag.String("check", "", `generates the security overview for test pourposes from a single check report stored in
can you add an example value, like: `ex: -check check_report.json` ? It was not clear to me that this was the json file containing the output of the check execution

2020-08-25 16:39 UTC, filewalkwithme commented on report.go
> +	d.Email, err = report.GenerateOverview(d.conf, d.awsConfig, d.conf.General.ResourcesPath, d.folder, reportData, d.teamName, d.teamID, d.scanID)
Do we need to generate the `Overview` part here? Maybe we can remove this.

2020-08-25 16:39 UTC, filewalkwithme commented on vulcan/vulcan.go
> +	log.Printf("Getting reports from results api...")
Oh, I think we can replace this log line by `Getting reports from results json file...`

2020-08-26 11:59 UTC, manelmontilla commented on cmd/vulcan-security-overview/main.go
> +	check      = flag.String("check", "", `generates the security overview for test pourposes from a single check report stored in
Yes thanks for the suggestion!!

2020-08-26 12:12 UTC, manelmontilla commented on report.go
> +	d.Email, err = report.GenerateOverview(d.conf, d.awsConfig, d.conf.General.ResourcesPath, d.folder, reportData, d.teamName, d.teamID, d.scanID)
Yes true!!

2020-08-26 12:12 UTC, manelmontilla commented on vulcan/vulcan.go
> +	log.Printf("Getting reports from results api...")
Yep thanks!!

2021-03-15 17:27 UTC, filewalkwithme approved these changes
LGTM

2021-03-15 17:28 UTC, merged